storages:
  default:
    path: "/var/backups/%{hostname}"
  external:
    path: "/mnt/external/backups/%{hostname}"

rotations:
  default:
    daily: 10   # keep up to 10 daily backups
    monthly: 12 # keep up to 12 monthly backups
    yearly: 3   # keep up to 3 yearly backups
  extended:
    hourly: 24  # keep up to 24 hourly backups
    daily: 10
    monthly: 12
    yearly: 5

exclude_sets:
  # be sure to define a default exclude set!
  default:
    - '/dev/*'
    - '/proc/*'
    - '/sys/*'
    - '/tmp/*'
    - '/run/*'
    - '/mnt/*'
    - '/media/*'
    - '/lost+found'
  alternative:
    - '/dev/*'
    - '/proc/*'
    - '/sys/*'
    - '/run/*'
    - '/lost+found'
    - '/var/log/*'

servers:
  peter:
    ssh_port: 2222
    rotation: extended
    excludes: # additional excludes
      - '/home/dont_backup_this_user/'
  nasibisibusi:
    ssh_host: 'nasi.bisi.busi.example.com'
    ssh_key: '/home/example/.ssh/id_dsa'
    storage: external
    exclude_set: alternative
